echo "example shell script for deployment 12345"
echo " ENV_VALUE shell script for deployment "
echo " $EBS2_FDEBS_SOURCE_SCRIPT Source Script "
echo " SECURED_Db_Password -- Encrypted Variable , EBS2_FDEBS_DB_PASSWORD"
echo " Proj_Property -- Project Property,FDEBS_APPLICATION_SHORT_NAME"
echo " Inp_Property -- Input Variable,FDEBS_INP_FAIL_IF_PATCH_IN_PROG"
